name: Update block-ops backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    name: Executing Brownie Tests
    
    steps:
      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Ganache
        run: npm install -g ganache-cli@6.10.2
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.10'
      - run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> .env
      - run: pip install -r requirements.txt
      - run: brownie test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          directory: ./reports/
          flags: unittests
          verbose: true